run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - revive

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment # Too strict/opinionated for most backend projects
  gosec:
    excludes:
      - G104 # errcheck handles unchecked errors better
  revive:
    rules:
      - name: exported
        disabled: true # Do not strictly force comments on every single exported symbol

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
