FROM golang:1.24-alpine

RUN apk add --no-cache git gcc musl-dev

WORKDIR /app

# Install Air for hot reloading and Goose for migrations
RUN go install github.com/air-verse/air@latest
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

ENV PATH="/go/bin:${PATH}"

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
